# Generated by Django 3.1.2 on 2020-10-08 20:43

import common.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(default='projects\\default.png', storage=common.storage.OverwriteStorage(), upload_to=projects.models.projectImageSavePath)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_project', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dt_project'],
            },
        ),
    ]
