# Generated by Django 3.1.2 on 2020-10-08 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201009_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dt_project',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
