# Generated by Django 3.1.2 on 2020-10-08 21:33

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201009_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects\\default.jpg', upload_to=projects.models.projectImageSavePath),
        ),
    ]
