# Generated by Django 3.1.2 on 2020-10-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201009_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='detail',
        ),
    ]
