# Generated by Django 3.1.2 on 2020-10-08 21:44

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201009_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.projectDownloadsSavePath),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects\\default_image.jpg', upload_to=projects.models.projectImageSavePath),
        ),
    ]
