# Generated by Django 3.1.2 on 2020-10-09 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('dt_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dt_added'],
            },
        ),
    ]
