# Generated by Django 3.1.2 on 2020-10-09 09:08

import common.models
import common.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(default='customers\\default_profile_picture.png', storage=common.storage.OverwriteStorage(), upload_to=common.models.custProfileImageSavePath)),
                ('review_quote', models.TextField()),
                ('dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_review', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dt_review'],
            },
        ),
    ]
