# Generated by Django 3.1.2 on 2020-10-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerReviews',
            new_name='CustomerReview',
        ),
    ]
