# Generated by Django 3.1.2 on 2020-10-09 10:01

import common.models
import common.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201009_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='customers\\default_profile_picture.png', storage=common.storage.OverwriteStorage(), upload_to=common.models.custProfileImageSavePath)),
                ('dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_show', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dt_show'],
            },
        ),
    ]
