# Generated by Django 3.1.2 on 2020-10-09 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201009_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dt_creation'],
            },
        ),
    ]
